### PR TITLE
fix Union and Interface type for federation

### PR DESCRIPTION
**Pull request by chedom**
Fix issue #276

### CODE REVIEW

**Comment by spetrunin** [comment]
@chedom We already have a basic integration test here https://github.com/jensneuse/graphql-go-tools/blob/master/pkg/graphql/execution_engine_v2_test.go#L521

Do you think you need a separate one?

**Comment by chedom** [comment]
> @chedom We already have a basic integration test here https://github.com/jensneuse/graphql-go-tools/blob/master/pkg/graphql/execution_engine_v2_test.go#L521
> 
> Do you think you need a separate one?

According to [comment](https://github.com/TykTechnologies/graphql-go-tools/pull/155#issuecomment-908270679) its required to add e2e tests for federation.
TestExecutionEngineV2_FederationAndSubscription_IntegrationTest skips important step - creating federation schema from SDLs.

**Comment by spetrunin** [comment]
@chedom it is not a hard requirement it is only nice to have

Also, I believe we could use existing subgraphs from examples to not copy over them - this will make a code a bit simpler

**Comment by chedom** [comment]
@spetrunin  I don't consider it as copying/duplicating.  In my opinion `examples` and `tests` exist for different purposes and, more importantly, they have different reason to change that's why I decided not to bind them.  But if you have a different opinion, I can redo.

**Pull request merged**
