### PR TITLE
Feature/add subscription to execution engine v2

### PR DESCRIPTION
**Pull request by chedom**
1. Add Subscription operation to execution engine V2

### CODE REVIEW

**Comment by jensneuse** [comment]
Can you extend the example with a federation API so that it can be tested?
Here's an example with a subscription upstream you could use:
https://github.com/wundergraph/wundergraph-demo/tree/main/federation/services/products

**Comment by chedom** [comment]
@jensneuse I have added test case for federation API.
Is that what you meant ?

**Comment by jensneuse** [comment]
> @jensneuse I have added test case for federation API.
> Is that what you meant ?

I would like to manually test federated subscriptions using a gqlgen example subgraph so that you can open the playground and see it in action.

**Comment by chedom** [comment]
Example has been added.

**Comment by jensneuse** [comment]
> Example has been added.

When I merge all 3 branches together, I get a merge conflict.
Can you create a clean PR with all code together without conflicts?
I'd really appreciate it.

**Comment by chedom** [comment]
> > Example has been added.
> 
> When I merge all 3 branches together, I get a merge conflict.
> Can you create a clean PR with all code together without conflicts?
> I'd really appreciate it.

Done. All code is in initial PR #250

**Comment by chedom** [comment]
Changes will be  in #250

**Pull request closed without merging**
